from typing import Callable

import paho.mqtt.client as paho_client
from elasticai.protocol.client_interface import PubSubInterface

class PublishError(Exception): ...
class SubscribeError(Exception): ...
class UnsubscribeError(Exception): ...

class MQTTClient(PubSubInterface):
    def __init__(
        self,
        client_id: str,
        clean_session: bool = False,
        mqtt_version: paho_client.MQTTProtocolVersion = ...,
        auto_reconnect: bool = True,
    ) -> None: ...
    def __del__(self) -> None: ...
    def connect(self, mqtt_broker_address: str, mqtt_broker_port: int) -> None: ...
    def disconnect(self) -> None: ...
    def get_client_id(self) -> str: ...
    def publish(self, topic: str, message: str, retain: bool = False) -> None: ...
    def subscribe(self, topic: str, handler: Callable[[str, str], None]) -> None: ...
    def unsubscribe(self, topic: str) -> None: ...
