# Workflow requires Variables to be defined as follows:
#   secrets.PUSH_TOKEN -> Password with rights to push to repository

name: "Create Release"
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  semantic_release:
    name: Generate Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      release_tag: ${{ steps.release.outputs.VERSION }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version: "lts/*"
      - name: Install semantic-release Plugin
        run: npm clean-install
      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures
      - name: Create Release
        id: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release