name: "PR Validation"
on:
  workflow_dispatch:
  pull_request:
    branches:
      - 'main'
jobs:
  lint-commits:
    name: Check Commit Message Style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Lint Commits
        uses: wagoid/commitlint-github-action@v6
        with:
          failOnWarnings: true
          failOnErrors: true
  clang-format:
    name: Check C Code Formatting
    needs:
      - lint-commits
    runs-on: ubuntu-latest
    strategy:
      matrix:
        path:
          - "C/src"
          - "C/test"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Run clang-format style check for C/C++/Protobuf programs.
        uses: jidicula/clang-format-action@v4.14.0
        with:
          clang-format-version: '17'
          check-path: ${{ matrix.path }}
          fallback-style: 'LLVM'
  unit-tests:
    name: Perform unit-tests for C Code
    needs:
      - clang-format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install build environment
        uses: lukka/get-cmake@v4.02
      - name: Setup CMake
        run: cmake --preset host
      - name: Build Targets
        run: cmake --build --preset unit_test
      - name: Run Unit-Tests
        run: ctest --preset unit_test
  pytest:
    name: Perform unit-tests for Python
    needs:
      - lint-commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: Install Python Environment
        run: |
          uv venv .venv
          uv sync --all-groups
      - name: Run Unit-Tests
        run: |
          uv run pytest
