name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unitTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: CMAKE
        working-directory: ${{github.workspace}}/build
        run: cmake -DTARGET_GROUP=test ..

      - name: Make all
        working-directory: ${{github.workspace}}/build
        run: make all

      - name: Run tests
        working-directory: ${{github.workspace}}/build
        run: ctest -V
