name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  unitTests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup CMake
        run: cmake -B cmake-build-debug -G Ninja .

      - name: Build test
        run: cmake --build cmake-build-debug -j 4

      - name: Run tests
        run: cmake --build cmake-build-debug -j 4
